apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketflow-config
  namespace: ticketflow
data:
  API_PORT: "4000"
  WORKER_PORT: "4100"
  LOG_LEVEL: "info"
  HOLD_TTL_SECONDS: "600"
  WORKER_CONCURRENCY: "5"
  PGHOST: "postgres"
  PGPORT: "5432"
  PGDATABASE: "ticketflow"
  PGUSER: "ticketflow"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PAYMENT_URL: "http://payment-gateway:4200"
  S3_ENDPOINT: "http://minio:9000"
  S3_PUBLIC_URL: "http://minio:9000"
  S3_BUCKET: "tickets"
  S3_REGION: "us-east-1"
